package com.example.instaflix.domain.model

data class SeriesDetail(
    val adult: Boolean,
    val backdropPath: String,
    val episodeRunTime: List<Int>,
    val firstAirDate: String?,
    val genres: List<Genre>,
    val homepage: String,
    val id: Int,
    val in_production: Boolean,
    val languages: List<String>,
    val lastAirDate: String?,
    val name: String,
    val nextEpisodeAir: String?,
    val numberEpisodes: Int,
    val numberSeasons: Int,
    val originCountry: List<String>,
    val originalLanguage: String,
    val originalName: String,
    val overview: String,
    val popularity: Double,
    val posterPath: String,
    val seasons: List<Season>,
    val status: String,
    val tagline: String,
    val type: String,
    val voteAverage: Double,
    val voteCount: Int,
)
